let imageCacheData = [
    './img/gorilla - Kopie (0).jpg',
    './img/gorilla - Kopie (1).jpg',
    './img/gorilla - Kopie (2).jpg',
    './img/gorilla - Kopie (3).jpg',
    './img/gorilla - Kopie (4).jpg',
    './img/gorilla - Kopie (5).jpg',
    './img/gorilla - Kopie (6).jpg',
    './img/gorilla - Kopie (7).jpg',
    './img/gorilla - Kopie (8).jpg',

    './img/lizard - Kopie (0).jpg',
    './img/lizard - Kopie (1).jpg',
    './img/lizard - Kopie (2).jpg',
    './img/lizard - Kopie (3).jpg',
    './img/lizard - Kopie (4).jpg',
    './img/lizard - Kopie (5).jpg',
    './img/lizard - Kopie (6).jpg',
    './img/lizard - Kopie (7).jpg',
    './img/lizard - Kopie (8).jpg',

    './img/man - Kopie (0).jpg',
    './img/man - Kopie (1).jpg',
    './img/man - Kopie (2).jpg',
    './img/man - Kopie (3).jpg',
    './img/man - Kopie (4).jpg',
    './img/man - Kopie (5).jpg',
    './img/man - Kopie (6).jpg',
    './img/man - Kopie (7).jpg',
    './img/man - Kopie (8).jpg',

    './img/tunnel - Kopie (0).jpg',
    './img/tunnel - Kopie (1).jpg',
    './img/tunnel - Kopie (2).jpg',
    './img/tunnel - Kopie (3).jpg',
    './img/tunnel - Kopie (4).jpg',
    './img/tunnel - Kopie (5).jpg',
    './img/tunnel - Kopie (6).jpg',
    './img/tunnel - Kopie (7).jpg',
    './img/tunnel - Kopie (8).jpg',   
]